# Generated by Django 4.1.5 on 2024-01-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
